stages:
  - build
  - test
  - push
  - deploy

build-and-push:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
      - docker login $DOCKER_REGISTRY_HOST -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASS
  script:
    - echo "Building image..."
    - docker buildx build --build-arg AVA_IMAGE_VERSION=$CI_COMMIT_REF_NAME -t $DOCKER_IMAGE_NAME:$CI_COMMIT_REF_NAME  .
    - echo "Built successfully"

    - echo "Pushing image..."
    - docker push $DOCKER_IMAGE_NAME:$CI_COMMIT_REF_NAME
    - echo "Pushed successfully ."
  only:
    # - teste
    - tags

deploy:
  stage: deploy
  before_script:
    # - if [ "$CI_COMMIT_REF_NAME" = 'proximo' ]; then export SSH_HOST='10.126.0.207'; fi
    # - if [ "$CI_COMMIT_REF_NAME" = 'teste' ]; then export SSH_HOST='10.22.1.217'; fi
    # - if [ "$CI_COMMIT_REF_NAME" = 'producao' ]; then export SSH_HOST='10.22.1.21'; fi
    - echo "Deploying service in $SSH_HOST..."
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
  script:
    - ssh -o StrictHostKeyChecking=no root@$SSH_HOST "sed -i 's/avamoodle:.*$/avamoodle:$CI_COMMIT_REF_NAME/g' /var/dockers/docker-compose.yml"
    - ssh -o StrictHostKeyChecking=no root@$SSH_HOST "cd /var/dockers && docker compose pull ava && docker compose down ava && docker compose up -d"
    - sleep 120
    - ssh -o StrictHostKeyChecking=no root@$SSH_HOST "cd /var/dockers && docker compose logs -n 1000"
    - echo "Service successfully deployed in $SSH_HOST."
  only:
    - tags
